thermanager: Ignore unused data variables
 * Ignore unused variables required by the APIs

 * src/main.c:64:37:
    error: unused parameter 'data'

 * src/resource.c:575:36:
    error: unused parameter 'data'

 * Apply the resolved warnings/errors
    to the Linux-based regular Makefile